version: '3.3'
services:
  moviematch:
    container_name: moviematch
    environment:
      - 'PLEX_URL=${PLEX_URL}' 
      - 'PLEX_TOKEN=${PLEX_TOKEN}'
    ports:
      - '127.0.0.1:8000:8000'
    image: lukechannings/moviematch
