version: '3.8'
services:
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/London
      - UMASK_SET=002
    volumes:
      - ${DOCKER_DIR}/radarr/config:/config
      - ${MOUNT_POINT}/data_root:/data_root
    ports:
      - 127.0.0.1:7878:7878
    networks:
      - download
    restart: unless-stopped
networks:
  download:
    name: download
