version: '3.8'
services:
  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/London
      - UMASK_SET=002
    volumes:
      # ssd
      - ${DOCKER_DIR}/nzbget/config:/config
      - ${INCOMPLETE_DIR}/nzbget:/incomplete
      # hdd
      - ${MOUNT_POINT}/data_root/nzbget:/data_root/nzbget
    ports:
      - 6789:6789
    networks:
      - download
    restart: unless-stopped
networks:
  download:
    name: download
