version: '3.8'
services:
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1002
      - TZ=Europe/London
      - AUTO_UPDATE=true
    volumes:
      - ${DOCKER_DIR}/jackett/config:/config
      - ${MOUNT_POINT}/data_root/transmission/complete:/downloads
    ports:
      - 9117:9117
    networks:
      - download
    restart: unless-stopped
networks:
  download:
    name: download
