version: "2.1"
services:
  nzbhydra2:
    image: ghcr.io/linuxserver/nzbhydra2
    container_name: nzbhydra2
    environment:
      - PUID=1000
      - PGID=1002
      - UMASK=002
      - TZ=Europe/London
    volumes:
      - ${DOCKER_DIR}/nzbhydra2/config:/config
      - ${MOUNT_POINT}/data_root/nzbhydra2/downloads:/downloads
    ports:
      - 127.0.0.1:5076:5076
    networks:
      - download
    restart: unless-stopped
networks:
  download:
    name: download